language: java
sudo: required
dist: trusty
install: skip
jdk: openjdk8
git:
  submodules: false
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - cd ..
  - ls
  - git clone https://github.com/papermc/paper
  - cd paper
  - ./paper p
  - mvn clean install
  
script: mvn clean install
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Minecraft'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master