main: main.Main
version: 0.1
api-version: 1.13
name: HoCore
depend: [SmartInvs]
commands:
   setspawn:
      description: Pone el Spawn
   spawn:
      description: Te Teletransporta al spawn.
   banhammer:
      description: Te da el gran poder del BanHammer en tus manos.
