main: main.UHCLebrel
version: 1.0.0
api-version: 1.16
name: UHCLebrel
description: All-in-one plugin designed for easily hosting UHC competitions and having server managment basic utils (Chat manager, spectation manager, etc...) .
authors: [Palomox]
depend: [PlaceholderAPI]
commands:
   c:
      description: Fires AsyncPlayerChatEvent
   channel: 
      description: Lets you change your channels.
   uhc:
      description: Main plugin command.
   createteam:
      description: Command for players to create teams.
