main: main.UHCLebrel
version: 1.0.0
api-version: 1.16
name: UHCLebrel
description: Plugin designed for easily hosting UHC competitions.
authors: [Palomox]
depend: [PlaceholderAPI]
commands:
   setspawn:
      description: Pone el Spawn
   spawn:
      description: Te Teletransporta al spawn.
   c:
      description: Lanza un evento de chat.
   sudo:
      description: Fuerzas a realizar un comando a alguien.
   channel: 
      description: Te permite dejar o unirte a un canal.
   uhc:
      description: Comando principal del plugin.
